import type { FarcasterRepliesResponse } from "@/types/types";

export const mockReplies: FarcasterRepliesResponse = {
  unrepliedCount: 3,
  unrepliedDetails: [
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
      username: "sophia",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      timeAgo: "2h",
      timestamp: 1716666666,
      authorFid: 123,
      castUrl: "https://farcaster.xyz/cast/123",
      castHash: "123",
      originalCastText: "Original text",
      originalCastHash: "123",
      originalAuthorUsername: "original_author",
      replyCount: 0,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
      username: "alex",
      text: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      timeAgo: "1h",
      timestamp: 1716666666,
      authorFid: 123,
      castUrl: "https://farcaster.xyz/cast/123",
      castHash: "123",
      originalCastText: "Original text",
      originalCastHash: "123",
      originalAuthorUsername: "original_author",
      replyCount: 0,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/65.jpg",
      username: "olivia",
      text: "Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
      timeAgo: "5m",
      timestamp: 1716666666,
      authorFid: 123,
      castUrl: "https://farcaster.xyz/cast/123",
      castHash: "123",
      originalCastText: "Original text",
      originalCastHash: "123",
      originalAuthorUsername: "original_author",
      replyCount: 0,
    },
  ],
  message: "Success",
};