import type { FarcasterRepliesResponse, ReplyTipsResponse } from "@/types/types";

export const mockReplies: FarcasterRepliesResponse = {
  unrepliedCount: 6,
  unrepliedDetails: [
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
      username: "sophia",
      text: "Check out this amazing video! https://youtu.be/avjI3_GIZBw It's absolutely incredible what they've accomplished.",
      timeAgo: "2h",
      timestamp: 1716666666,
      authorFid: 123,
      castUrl: "https://farcaster.xyz/cast/123",
      castHash: "123",
      originalCastText: "Original text",
      originalCastHash: "123",
      originalAuthorUsername: "original_author",
      replyCount: 5,
      likesCount: 12,
      recastsCount: 3,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
      username: "alex",
      text: "Here's a beautiful photo I took: https://picsum.photos/800/600 and also check out this website: https://example.com",
      timeAgo: "1h",
      timestamp: 1716666666,
      authorFid: 124,
      castUrl: "https://farcaster.xyz/cast/124",
      castHash: "124",
      originalCastText: "Original text",
      originalCastHash: "124",
      originalAuthorUsername: "original_author",
      replyCount: 2,
      likesCount: 8,
      recastsCount: 1,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/65.jpg",
      username: "olivia",
      text: "Just watched this incredible performance: https://youtu.be/dQw4w9WgXcQ and here's a cool image: https://picsum.photos/400/300",
      timeAgo: "5m",
      timestamp: 1716666666,
      authorFid: 125,
      castUrl: "https://farcaster.xyz/cast/125",
      castHash: "125",
      originalCastText: "Original text",
      originalCastHash: "125",
      originalAuthorUsername: "original_author",
      replyCount: 7,
      likesCount: 15,
      recastsCount: 4,
      userLiked: true,
      hasUserInteraction: true,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
      username: "mike",
      text: "Found this interesting article: https://farcaster.xyz and some great photos: https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
      timeAgo: "30m",
      timestamp: 1716666666,
      authorFid: 126,
      castUrl: "https://farcaster.xyz/cast/126",
      castHash: "126",
      originalCastText: "Original text",
      originalCastHash: "126",
      originalAuthorUsername: "original_author",
      replyCount: 3,
      likesCount: 6,
      recastsCount: 2,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
      username: "sarah",
      text: "Check out this amazing song: https://open.spotify.com/track/5VP1yXviUwA0KA0ewit5pe?si=4ad99b84f89a461a It's absolutely beautiful!",
      timeAgo: "20m",
      timestamp: 1716666666,
      authorFid: 128,
      castUrl: "https://farcaster.xyz/cast/128",
      castHash: "128",
      originalCastText: "Original text",
      originalCastHash: "128",
      originalAuthorUsername: "original_author",
      replyCount: 4,
      likesCount: 9,
      recastsCount: 3,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/23.jpg",
      username: "emma",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. No links in this one, just plain text.",
      timeAgo: "15m",
      timestamp: 1716666666,
      authorFid: 127,
      castUrl: "https://farcaster.xyz/cast/127",
      castHash: "127",
      originalCastText: "Original text",
      originalCastHash: "127",
      originalAuthorUsername: "original_author",
      replyCount: 1,
      likesCount: 3,
      recastsCount: 0,
      userRecasted: true,
      hasUserInteraction: true,
    },
  ],
  message: "Successfully fetched unreplied conversations",
  nextCursor: null,
};

// Mock data for $REPLY tips
export const mockReplyTips: ReplyTipsResponse = {
  tipsReceived: [
    {
      amount: 5000,
      timestamp: Math.floor(Date.now() / 1000) - 3600, // 1 hour ago
      castHash: "0x1234567890abcdef",
      castText: "Amazing work on this project! 5000 $REPLY",
      castUrl: "https://farcaster.xyz/cast/0x1234567890abcdef",
      authorFid: 123456,
      authorUsername: "alice",
      authorDisplayName: "Alice",
      authorPfpUrl: "https://randomuser.me/api/portraits/women/68.jpg",
      isTipGiven: false,
    },
    {
      amount: 10000,
      timestamp: Math.floor(Date.now() / 1000) - 7200, // 2 hours ago
      castHash: "0xabcdef1234567890",
      castText: "This is incredible! Here's 10000 $REPLY for your efforts",
      castUrl: "https://farcaster.xyz/cast/0xabcdef1234567890",
      authorFid: 789012,
      authorUsername: "bob",
      authorDisplayName: "Bob",
      authorPfpUrl: "https://randomuser.me/api/portraits/men/32.jpg",
      isTipGiven: false,
    },
    {
      amount: 2500,
      timestamp: Math.floor(Date.now() / 1000) - 86400, // 1 day ago
      castHash: "0x9876543210fedcba",
      castText: "Great insights! 2500 $REPLY",
      castUrl: "https://farcaster.xyz/cast/0x9876543210fedcba",
      authorFid: 345678,
      authorUsername: "charlie",
      authorDisplayName: "Charlie",
      authorPfpUrl: "https://randomuser.me/api/portraits/men/45.jpg",
      isTipGiven: false,
    },
  ],
  tipsGiven: [
    {
      amount: 3000,
      timestamp: Math.floor(Date.now() / 1000) - 1800, // 30 minutes ago
      castHash: "0xfedcba0987654321",
      castText: "Thanks for sharing this! 3000 $REPLY",
      castUrl: "https://farcaster.xyz/cast/0xfedcba0987654321",
      authorFid: 203666, // Current user
      authorUsername: "user",
      authorDisplayName: "Current User",
      authorPfpUrl: "https://randomuser.me/api/portraits/men/1.jpg",
      isTipGiven: true,
    },
    {
      amount: 7500,
      timestamp: Math.floor(Date.now() / 1000) - 5400, // 1.5 hours ago
      castHash: "0x1122334455667788",
      castText: "This is exactly what I needed! 7500 $REPLY",
      castUrl: "https://farcaster.xyz/cast/0x1122334455667788",
      authorFid: 203666, // Current user
      authorUsername: "user",
      authorDisplayName: "Current User",
      authorPfpUrl: "https://randomuser.me/api/portraits/men/1.jpg",
      isTipGiven: true,
    },
    {
      amount: 1500,
      timestamp: Math.floor(Date.now() / 1000) - 90000, // 1 day ago
      castHash: "0x9988776655443322",
      castText: "Nice work! 1500 $REPLY",
      castUrl: "https://farcaster.xyz/cast/0x9988776655443322",
      authorFid: 203666, // Current user
      authorUsername: "user",
      authorDisplayName: "Current User",
      authorPfpUrl: "https://randomuser.me/api/portraits/men/1.jpg",
      isTipGiven: true,
    },
  ],
  totalReceived: 17500,
  totalGiven: 12000,
  totalReceivedToday: 15000, // 5000 + 10000 (from today)
  totalGivenToday: 10500, // 3000 + 7500 (from today)
  message: "Successfully fetched $REPLY tips",
  nextCursor: null,
};
