import type { FarcasterRepliesResponse } from "@/types/types";

export const mockReplies: FarcasterRepliesResponse = {
  unrepliedCount: 6,
  unrepliedDetails: [
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
      username: "sophia",
      text: "Check out this amazing video! https://youtu.be/avjI3_GIZBw It's absolutely incredible what they've accomplished.",
      timeAgo: "2h",
      timestamp: 1716666666,
      authorFid: 123,
      castUrl: "https://farcaster.xyz/cast/123",
      castHash: "123",
      originalCastText: "Original text",
      originalCastHash: "123",
      originalAuthorUsername: "original_author",
      replyCount: 5,
      likesCount: 12,
      recastsCount: 3,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
      username: "alex",
      text: "Here's a beautiful photo I took: https://picsum.photos/800/600 and also check out this website: https://example.com",
      timeAgo: "1h",
      timestamp: 1716666666,
      authorFid: 124,
      castUrl: "https://farcaster.xyz/cast/124",
      castHash: "124",
      originalCastText: "Original text",
      originalCastHash: "124",
      originalAuthorUsername: "original_author",
      replyCount: 2,
      likesCount: 8,
      recastsCount: 1,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/65.jpg",
      username: "olivia",
      text: "Just watched this incredible performance: https://youtu.be/dQw4w9WgXcQ and here's a cool image: https://picsum.photos/400/300",
      timeAgo: "5m",
      timestamp: 1716666666,
      authorFid: 125,
      castUrl: "https://farcaster.xyz/cast/125",
      castHash: "125",
      originalCastText: "Original text",
      originalCastHash: "125",
      originalAuthorUsername: "original_author",
      replyCount: 7,
      likesCount: 15,
      recastsCount: 4,
      userLiked: true,
      hasUserInteraction: true,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
      username: "mike",
      text: "Found this interesting article: https://farcaster.xyz and some great photos: https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
      timeAgo: "30m",
      timestamp: 1716666666,
      authorFid: 126,
      castUrl: "https://farcaster.xyz/cast/126",
      castHash: "126",
      originalCastText: "Original text",
      originalCastHash: "126",
      originalAuthorUsername: "original_author",
      replyCount: 3,
      likesCount: 6,
      recastsCount: 2,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
      username: "sarah",
      text: "Check out this amazing song: https://open.spotify.com/track/5VP1yXviUwA0KA0ewit5pe?si=4ad99b84f89a461a It's absolutely beautiful!",
      timeAgo: "20m",
      timestamp: 1716666666,
      authorFid: 128,
      castUrl: "https://farcaster.xyz/cast/128",
      castHash: "128",
      originalCastText: "Original text",
      originalCastHash: "128",
      originalAuthorUsername: "original_author",
      replyCount: 4,
      likesCount: 9,
      recastsCount: 3,
    },
    {
      avatarUrl: "https://randomuser.me/api/portraits/women/23.jpg",
      username: "emma",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. No links in this one, just plain text.",
      timeAgo: "15m",
      timestamp: 1716666666,
      authorFid: 127,
      castUrl: "https://farcaster.xyz/cast/127",
      castHash: "127",
      originalCastText: "Original text",
      originalCastHash: "127",
      originalAuthorUsername: "original_author",
      replyCount: 1,
      likesCount: 3,
      recastsCount: 0,
      userRecasted: true,
      hasUserInteraction: true,
    },
  ],
  message: "Success",
};
